unit GlutFonts;

(****
  BRY:  This unit was ported from the OpenGLUT file og_font_data.c,
    as well as from a freeglut-developer mailing list post by
    Nigel Stewart.  Original og_font_data.c license follows
****)

(*
 * This file has been automatically generated by the 
 * genfonts utility.  It has been manually tweaked for
 * some glyphs.
 *
 * The legal status of this file is a bit vague.  The font glyphs
 * themselves come from XFree86 v4.3.0 (as of this writing), and as
 * part of the X server may be subject to the XFree86 copyrights.
 * The original freeglut fonts were extracted by a utility written
 * by Pawel W. Olszta (see below) and the generated fonts contained
 * his copyright exclusively.  Steve Baker asserts that Pawel
 * assigned intellectual property rights to Steve Baker.  Steve
 * Baker also asserts that fonts cannot be copyrighted.  He has
 * neither stripped the copyright from the freeglut fonts nor
 * formally retitled anything in his name.  Since that time, the
 * OpenGLUT project has branched from freeglut, and has made
 * necessary modifications to Pawel's ``genfonts'' utility.
 * To that extent, OpenGLUT may have some title to this file.
 * What is fairly clear is that the font data is licensed under
 * the XFree86 license (which is variously termed ``XFree'' and
 * ``MIT'' by the freeglut project).  It is believed that all
 * title holders wish this file to be as useful as possible, and
 * that either the ``XFree'' or ``MIT'' license works.
 *
 * Portions copyright (c) 2004, the OpenGLUT project contributors.
 * OpenGLUT branched from freeglut in February, 2004.
 *
 * Copyright (c) 1999-2000 by Pawel W. Olszta
 * Written by Pawel W. Olszta, <olszta@sourceforge.net>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Sotware.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * PAWEL W. OLSZTA BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *)

interface

uses
  SysUtils, GL;

const
  GLUT_BITMAP_HELVETICA_10 = 6;
  GLUT_BITMAP_HELVETICA_12 = 7;

procedure glutBitmapString(fontID: integer; const s: string);

implementation

type
  PGLUBCharMapArray = ^TGLUBCharMapArray;
  TGLUBCharMapArray = array[0..255] of PGLubyte;

  PGLUTFontDef = ^TGLUTFontDef;
  TGLUTFontDef = record
    charcnt:  GLushort;
    height:   GLubyte;
    chars:    PGLUBCharMapArray;
    xorig:    GLubyte;
    yorig:    GLubyte;
  end;


const
Helvetica10_Character_000: array[0..14] of GLubyte = (  8,  0,  0,  0, 84,  0, 68,  0, 68,  0, 84,  0,  0,  0,  0);
Helvetica10_Character_001: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_002: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_003: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_004: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_005: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_006: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_007: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_008: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_009: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_010: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_011: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_012: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_013: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_014: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_015: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_016: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_017: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_018: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_019: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_020: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_021: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_022: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_023: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_024: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_025: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_026: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_027: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_028: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_029: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_030: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_031: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_032: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_033: array[0..14] of GLubyte = (  3,  0,  0,  0, 64,  0, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica10_Character_034: array[0..14] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,  0,  0, 80, 80,  0,  0,  0);
Helvetica10_Character_035: array[0..14] of GLubyte = (  6,  0,  0,  0, 80, 80,248, 40,124, 40, 40,  0,  0,  0,  0);
Helvetica10_Character_036: array[0..14] of GLubyte = (  6,  0,  0, 32,112,168, 40,112,160,168,112, 32,  0,  0,  0);
Helvetica10_Character_037: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 38,  0, 41,  0, 22,  0, 16,  0,  8,  0,104,  0,148,  0,100,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_038: array[0..14] of GLubyte = (  8,  0,  0,  0, 50, 76, 76, 82, 48, 40, 40, 16,  0,  0,  0);
Helvetica10_Character_039: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0, 64, 32, 32,  0,  0,  0);
Helvetica10_Character_040: array[0..14] of GLubyte = (  4,  0, 32, 64, 64,128,128,128,128, 64, 64, 32,  0,  0,  0);
Helvetica10_Character_041: array[0..14] of GLubyte = (  4,  0, 64, 32, 32, 16, 16, 16, 16, 32, 32, 64,  0,  0,  0);
Helvetica10_Character_042: array[0..14] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,  0,160, 64,160,  0,  0,  0);
Helvetica10_Character_043: array[0..14] of GLubyte = (  6,  0,  0,  0,  0, 32, 32,248, 32, 32,  0,  0,  0,  0,  0);
Helvetica10_Character_044: array[0..14] of GLubyte = (  3,  0,128, 64, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_045: array[0..14] of GLubyte = (  7,  0,  0,  0,  0,  0,  0,124,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_046: array[0..14] of GLubyte = (  3,  0,  0,  0, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_047: array[0..14] of GLubyte = (  3,  0,  0,  0,128,128, 64, 64, 64, 64, 32, 32,  0,  0,  0);
Helvetica10_Character_048: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,136,136,112,  0,  0,  0);
Helvetica10_Character_049: array[0..14] of GLubyte = (  6,  0,  0,  0, 32, 32, 32, 32, 32, 32, 96, 32,  0,  0,  0);
Helvetica10_Character_050: array[0..14] of GLubyte = (  6,  0,  0,  0,248,128, 64, 48,  8,  8,136,112,  0,  0,  0);
Helvetica10_Character_051: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,  8,  8, 48,  8,136,112,  0,  0,  0);
Helvetica10_Character_052: array[0..14] of GLubyte = (  6,  0,  0,  0, 16, 16,248,144, 80, 80, 48, 16,  0,  0,  0);
Helvetica10_Character_053: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,  8,  8,240,128,128,248,  0,  0,  0);
Helvetica10_Character_054: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,200,176,128,136,112,  0,  0,  0);
Helvetica10_Character_055: array[0..14] of GLubyte = (  6,  0,  0,  0, 64, 64, 32, 32, 16, 16,  8,248,  0,  0,  0);
Helvetica10_Character_056: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,112,136,136,112,  0,  0,  0);
Helvetica10_Character_057: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,  8,104,152,136,136,112,  0,  0,  0);
Helvetica10_Character_058: array[0..14] of GLubyte = (  3,  0,  0,  0, 64,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0);
Helvetica10_Character_059: array[0..14] of GLubyte = (  3,  0,128, 64, 64,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0);
Helvetica10_Character_060: array[0..14] of GLubyte = (  6,  0,  0,  0,  0, 16, 32, 64, 32, 16,  0,  0,  0,  0,  0);
Helvetica10_Character_061: array[0..14] of GLubyte = (  5,  0,  0,  0,  0,  0,240,  0,240,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_062: array[0..14] of GLubyte = (  6,  0,  0,  0,  0, 64, 32, 16, 32, 64,  0,  0,  0,  0,  0);
Helvetica10_Character_063: array[0..14] of GLubyte = (  6,  0,  0,  0, 32,  0, 32, 32, 16,  8, 72, 48,  0,  0,  0);
Helvetica10_Character_064: array[0..28] of GLubyte = ( 11,  0,  0, 62,  0, 64,  0,155,  0,164,128,164,128,162, 64,146, 64, 77, 64, 32,128, 31,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_065: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16,  0,  0,  0);
Helvetica10_Character_066: array[0..14] of GLubyte = (  7,  0,  0,  0,120, 68, 68, 68,120, 68, 68,120,  0,  0,  0);
Helvetica10_Character_067: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 64, 64, 64, 64, 66, 60,  0,  0,  0);
Helvetica10_Character_068: array[0..14] of GLubyte = (  8,  0,  0,  0,120, 68, 66, 66, 66, 66, 68,120,  0,  0,  0);
Helvetica10_Character_069: array[0..14] of GLubyte = (  7,  0,  0,  0,124, 64, 64, 64,124, 64, 64,124,  0,  0,  0);
Helvetica10_Character_070: array[0..14] of GLubyte = (  6,  0,  0,  0, 64, 64, 64, 64,120, 64, 64,124,  0,  0,  0);
Helvetica10_Character_071: array[0..14] of GLubyte = (  8,  0,  0,  0, 58, 70, 66, 70, 64, 64, 66, 60,  0,  0,  0);
Helvetica10_Character_072: array[0..14] of GLubyte = (  8,  0,  0,  0, 66, 66, 66, 66,126, 66, 66, 66,  0,  0,  0);
Helvetica10_Character_073: array[0..14] of GLubyte = (  3,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica10_Character_074: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144, 16, 16, 16, 16, 16, 16,  0,  0,  0);
Helvetica10_Character_075: array[0..14] of GLubyte = (  7,  0,  0,  0, 68, 68, 72, 72,112, 80, 72, 68,  0,  0,  0);
Helvetica10_Character_076: array[0..14] of GLubyte = (  6,  0,  0,  0,120, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica10_Character_077: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 73,  0, 73,  0, 73,  0, 85,  0, 85,  0, 99,  0, 99,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_078: array[0..14] of GLubyte = (  8,  0,  0,  0, 70, 70, 74, 74, 82, 82, 98, 98,  0,  0,  0);
Helvetica10_Character_079: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 60,  0,  0,  0);
Helvetica10_Character_080: array[0..14] of GLubyte = (  7,  0,  0,  0, 64, 64, 64, 64,120, 68, 68,120,  0,  0,  0);
Helvetica10_Character_081: array[0..14] of GLubyte = (  8,  0,  0,  1, 62, 70, 74, 66, 66, 66, 66, 60,  0,  0,  0);
Helvetica10_Character_082: array[0..14] of GLubyte = (  7,  0,  0,  0, 68, 68, 68, 68,120, 68, 68,120,  0,  0,  0);
Helvetica10_Character_083: array[0..14] of GLubyte = (  7,  0,  0,  0, 56, 68, 68,  4, 56, 64, 68, 56,  0,  0,  0);
Helvetica10_Character_084: array[0..14] of GLubyte = (  5,  0,  0,  0, 32, 32, 32, 32, 32, 32, 32,248,  0,  0,  0);
Helvetica10_Character_085: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66,  0,  0,  0);
Helvetica10_Character_086: array[0..14] of GLubyte = (  7,  0,  0,  0, 16, 40, 40, 68, 68, 68,130,130,  0,  0,  0);
Helvetica10_Character_087: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 34,  0, 34,  0, 34,  0, 85,  0, 73,  0, 73,  0,136,128,136,128,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_088: array[0..14] of GLubyte = (  7,  0,  0,  0, 68, 68, 40, 40, 16, 40, 68, 68,  0,  0,  0);
Helvetica10_Character_089: array[0..14] of GLubyte = (  7,  0,  0,  0, 16, 16, 16, 40, 40, 68, 68,130,  0,  0,  0);
Helvetica10_Character_090: array[0..14] of GLubyte = (  7,  0,  0,  0,124, 64, 32, 16, 16,  8,  4,124,  0,  0,  0);
Helvetica10_Character_091: array[0..14] of GLubyte = (  3,  0, 96, 64, 64, 64, 64, 64, 64, 64, 64, 96,  0,  0,  0);
Helvetica10_Character_092: array[0..14] of GLubyte = (  3,  0,  0,  0, 32, 32, 64, 64, 64, 64,128,128,  0,  0,  0);
Helvetica10_Character_093: array[0..14] of GLubyte = (  3,  0,192, 64, 64, 64, 64, 64, 64, 64, 64,192,  0,  0,  0);
Helvetica10_Character_094: array[0..14] of GLubyte = (  6,  0,  0,  0,  0,  0,  0,136, 80, 80, 32, 32,  0,  0,  0);
Helvetica10_Character_095: array[0..14] of GLubyte = (  6,  0,252,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_096: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0, 63, 64, 32,  0,  0,  0);
Helvetica10_Character_097: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224,  0,  0,  0,  0,  0);
Helvetica10_Character_098: array[0..14] of GLubyte = (  6,  0,  0,  0,176,200,136,136,200,176,128,128,  0,  0,  0);
Helvetica10_Character_099: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144,128,128,144, 96,  0,  0,  0,  0,  0);
Helvetica10_Character_100: array[0..14] of GLubyte = (  6,  0,  0,  0,104,152,136,136,152,104,  8,  8,  0,  0,  0);
Helvetica10_Character_101: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144,128,240,144, 96,  0,  0,  0,  0,  0);
Helvetica10_Character_102: array[0..14] of GLubyte = (  4,  0,  0,  0, 64, 64, 64, 64, 64,224, 64, 48,  0,  0,  0);
Helvetica10_Character_103: array[0..14] of GLubyte = (  6,  0,112,  8,104,152,136,136,152,104,  0,  0,  0,  0,  0);
Helvetica10_Character_104: array[0..14] of GLubyte = (  6,  0,  0,  0,136,136,136,136,200,176,128,128,  0,  0,  0);
Helvetica10_Character_105: array[0..14] of GLubyte = (  2,  0,  0,  0,128,128,128,128,128,128,  0,128,  0,  0,  0);
Helvetica10_Character_106: array[0..14] of GLubyte = (  2,  0,  0,128,128,128,128,128,128,128,  0,128,  0,  0,  0);
Helvetica10_Character_107: array[0..14] of GLubyte = (  5,  0,  0,  0,144,144,160,192,160,144,128,128,  0,  0,  0);
Helvetica10_Character_108: array[0..14] of GLubyte = (  2,  0,  0,  0,128,128,128,128,128,128,128,128,  0,  0,  0);
Helvetica10_Character_109: array[0..14] of GLubyte = (  8,  0,  0,  0,146,146,146,146,146,236,  0,  0,  0,  0,  0);
Helvetica10_Character_110: array[0..14] of GLubyte = (  6,  0,  0,  0,136,136,136,136,200,176,  0,  0,  0,  0,  0);
Helvetica10_Character_111: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,112,  0,  0,  0,  0,  0);
Helvetica10_Character_112: array[0..14] of GLubyte = (  6,  0,128,128,176,200,136,136,200,176,  0,  0,  0,  0,  0);
Helvetica10_Character_113: array[0..14] of GLubyte = (  6,  0,  8,  8,104,152,136,136,152,104,  0,  0,  0,  0,  0);
Helvetica10_Character_114: array[0..14] of GLubyte = (  4,  0,  0,  0,128,128,128,128,192,160,  0,  0,  0,  0,  0);
Helvetica10_Character_115: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144, 16, 96,144, 96,  0,  0,  0,  0,  0);
Helvetica10_Character_116: array[0..14] of GLubyte = (  4,  0,  0,  0, 96, 64, 64, 64, 64,224, 64, 64,  0,  0,  0);
Helvetica10_Character_117: array[0..14] of GLubyte = (  5,  0,  0,  0,112,144,144,144,144,144,  0,  0,  0,  0,  0);
Helvetica10_Character_118: array[0..14] of GLubyte = (  6,  0,  0,  0, 32, 32, 80, 80,136,136,  0,  0,  0,  0,  0);
Helvetica10_Character_119: array[0..14] of GLubyte = (  8,  0,  0,  0, 40, 40, 84, 84,146,146,  0,  0,  0,  0,  0);
Helvetica10_Character_120: array[0..14] of GLubyte = (  6,  0,  0,  0,136,136, 80, 32, 80,136,  0,  0,  0,  0,  0);
Helvetica10_Character_121: array[0..14] of GLubyte = (  5,  0,128, 64, 64, 96,160,160,144,144,  0,  0,  0,  0,  0);
Helvetica10_Character_122: array[0..14] of GLubyte = (  5,  0,  0,  0,240,128, 64, 32, 16,240,  0,  0,  0,  0,  0);
Helvetica10_Character_123: array[0..14] of GLubyte = (  3,  0, 32, 64, 64, 64, 64,128, 64, 64, 64, 32,  0,  0,  0);
Helvetica10_Character_124: array[0..14] of GLubyte = (  3,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica10_Character_125: array[0..14] of GLubyte = (  3,  0,128, 64, 64, 64, 64, 32, 64, 64, 64,128,  0,  0,  0);
Helvetica10_Character_126: array[0..14] of GLubyte = (  7,  0,  0,  0,  0,  0,  0,152,100,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_127: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_128: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_129: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_130: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_131: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_132: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_133: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_134: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_135: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_136: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_137: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_138: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_139: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_140: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_141: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_142: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_143: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_144: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_145: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_146: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_147: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_148: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_149: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_150: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_151: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_152: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_153: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_154: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_155: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_156: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_157: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_158: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_159: array[0..28] of GLubyte = ( 13,  0,  0,  0,  0,  0,  0, 84,  0,  0,  0, 68,  0,  0,  0, 68,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_160: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_161: array[0..14] of GLubyte = (  3,  0, 64, 64, 64, 64, 64, 64,  0, 64,  0,  0,  0,  0,  0);
Helvetica10_Character_162: array[0..14] of GLubyte = (  6,  0,  0, 64,112,168,160,160,168,112, 16,  0,  0,  0,  0);
Helvetica10_Character_163: array[0..14] of GLubyte = (  6,  0,  0,  0,176, 72, 64, 64,224, 64, 72, 48,  0,  0,  0);
Helvetica10_Character_164: array[0..14] of GLubyte = (  5,  0,  0,  0,  0,144, 96,144,144, 96,144,  0,  0,  0,  0);
Helvetica10_Character_165: array[0..14] of GLubyte = (  6,  0,  0,  0, 32,248, 32,248, 80, 80,136,136,  0,  0,  0);
Helvetica10_Character_166: array[0..14] of GLubyte = (  3,  0, 64, 64, 64, 64,  0,  0, 64, 64, 64, 64,  0,  0,  0);
Helvetica10_Character_167: array[0..14] of GLubyte = (  6,  0,112,136, 24,112,200,152,112,192,136,112,  0,  0,  0);
Helvetica10_Character_168: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,160,  0,  0,  0);
Helvetica10_Character_169: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 28,  0, 34,  0, 77,  0, 81,  0, 77,  0, 34,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_170: array[0..14] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,224,  0,160, 32,224,  0,  0,  0);
Helvetica10_Character_171: array[0..14] of GLubyte = (  6,  0,  0,  0, 40, 80,160, 80, 40,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_172: array[0..14] of GLubyte = (  7,  0,  0,  0,  0,  0,  4,  4,124,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_173: array[0..14] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,224,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_174: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 28,  0, 34,  0, 85,  0, 89,  0, 93,  0, 34,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_175: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,224,  0,  0,  0);
Helvetica10_Character_176: array[0..14] of GLubyte = (  4,  0,  0,  0,  0,  0,  0, 96,144,144, 96,  0,  0,  0,  0);
Helvetica10_Character_177: array[0..14] of GLubyte = (  6,  0,  0,  0,248,  0, 32, 32,248, 32, 32,  0,  0,  0,  0);
Helvetica10_Character_178: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,224, 64,160, 96,  0,  0,  0,  0);
Helvetica10_Character_179: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,192, 32, 64,224,  0,  0,  0,  0);
Helvetica10_Character_180: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,128, 64,  0,  0,  0);
Helvetica10_Character_181: array[0..14] of GLubyte = (  5,  0,128,128,240,144,144,144,144,144,  0,  0,  0,  0,  0);
Helvetica10_Character_182: array[0..14] of GLubyte = (  6,  0, 40, 40, 40, 40, 40,104,232,232,232,124,  0,  0,  0);
Helvetica10_Character_183: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,192,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_184: array[0..14] of GLubyte = (  3,  0,192, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_185: array[0..14] of GLubyte = (  3,  0,  0,  0,  0,  0,  0, 64, 64,192, 64,  0,  0,  0,  0);
Helvetica10_Character_186: array[0..14] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,224,  0,224,160,224,  0,  0,  0);
Helvetica10_Character_187: array[0..14] of GLubyte = (  6,  0,  0,  0,160, 80, 40, 80,160,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_188: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 33,  0, 23,128, 19,  0,  9,  0, 72,  0, 68,  0,196,  0, 66,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_189: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 39,  0, 18,  0, 21,  0, 11,  0, 72,  0, 68,  0,196,  0, 66,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_190: array[0..28] of GLubyte = (  9,  0,  0,  0,  0,  0,  0, 33,  0, 23,128, 19,  0,  9,  0,200,  0, 36,  0, 68,  0,226,  0,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_191: array[0..14] of GLubyte = (  6,  0, 48, 72, 64, 32, 16, 16,  0, 16,  0,  0,  0,  0,  0);
Helvetica10_Character_192: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16,  0, 16, 32);
Helvetica10_Character_193: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16,  0, 16,  8);
Helvetica10_Character_194: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16,  0, 40, 16);
Helvetica10_Character_195: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16,  0, 40, 20);
Helvetica10_Character_196: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16,  0, 40,  0);
Helvetica10_Character_197: array[0..14] of GLubyte = (  7,  0,  0,  0,130,130,124, 68, 40, 40, 16, 16, 16, 40, 16);
Helvetica10_Character_198: array[0..28] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,143,128,136,  0,120,  0, 72,  0, 47,128, 40,  0, 24,  0, 31,128,  0,  0,  0,  0,  0,  0);
Helvetica10_Character_199: array[0..14] of GLubyte = (  8,  0, 24,  8, 60, 66, 64, 64, 64, 64, 66, 60,  0,  0,  0);
Helvetica10_Character_200: array[0..14] of GLubyte = (  7,  0,  0,  0,124, 64, 64, 64,124, 64, 64,124,  0, 16, 32);
Helvetica10_Character_201: array[0..14] of GLubyte = (  7,  0,  0,  0,124, 64, 64, 64,124, 64, 64,124,  0, 16,  8);
Helvetica10_Character_202: array[0..14] of GLubyte = (  7,  0,  0,  0,124, 64, 64,124, 64, 64, 64,124,  0, 40, 16);
Helvetica10_Character_203: array[0..14] of GLubyte = (  7,  0,  0,  0,124, 64, 64, 64,124, 64, 64,124,  0, 40,  0);
Helvetica10_Character_204: array[0..14] of GLubyte = (  3,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64,  0, 64,128);
Helvetica10_Character_205: array[0..14] of GLubyte = (  3,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64,  0, 64, 32);
Helvetica10_Character_206: array[0..14] of GLubyte = (  3,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64,  0,160, 64);
Helvetica10_Character_207: array[0..14] of GLubyte = (  3,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64,  0,160,  0);
Helvetica10_Character_208: array[0..14] of GLubyte = (  8,  0,  0,  0,120, 68, 66, 66,242, 66, 68,120,  0,  0,  0);
Helvetica10_Character_209: array[0..14] of GLubyte = (  8,  0,  0,  0, 70, 70, 74, 74, 82, 82, 98, 98,  0, 40, 20);
Helvetica10_Character_210: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 60,  0,  8, 16);
Helvetica10_Character_211: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 60,  0,  8,  4);
Helvetica10_Character_212: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 60,  0, 20,  8);
Helvetica10_Character_213: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 60,  0, 40, 20);
Helvetica10_Character_214: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 60,  0, 36,  0);
Helvetica10_Character_215: array[0..14] of GLubyte = (  6,  0,  0,  0,  0,136, 80, 32, 80,136,  0,  0,  0,  0,  0);
Helvetica10_Character_216: array[0..14] of GLubyte = (  8,  0,  0, 64, 60, 98, 82, 82, 74, 74, 70, 60,  2,  0,  0);
Helvetica10_Character_217: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66,  0,  8, 16);
Helvetica10_Character_218: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66,  0, 16,  8);
Helvetica10_Character_219: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66,  0, 20,  8);
Helvetica10_Character_220: array[0..14] of GLubyte = (  8,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66,  0, 36,  0);
Helvetica10_Character_221: array[0..14] of GLubyte = (  7,  0,  0,  0, 16, 16, 16, 40, 40, 68, 68,130,  0, 16,  8);
Helvetica10_Character_222: array[0..14] of GLubyte = (  7,  0,  0,  0, 64, 64,120, 68, 68,120, 64, 64,  0,  0,  0);
Helvetica10_Character_223: array[0..14] of GLubyte = (  5,  0,  0,  0,160,144,144,144,160,144,144, 96,  0,  0,  0);
Helvetica10_Character_224: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224,  0, 32, 64,  0,  0);
Helvetica10_Character_225: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224,  0, 32, 16,  0,  0);
Helvetica10_Character_226: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224,  0, 80, 32,  0,  0);
Helvetica10_Character_227: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224,  0,160, 80,  0,  0);
Helvetica10_Character_228: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224,  0, 80,  0,  0,  0);
Helvetica10_Character_229: array[0..14] of GLubyte = (  5,  0,  0,  0,104,144,144,112, 16,224, 32, 80, 32,  0,  0);
Helvetica10_Character_230: array[0..14] of GLubyte = (  8,  0,  0,  0,108,146,144,126, 18,236,  0,  0,  0,  0,  0);
Helvetica10_Character_231: array[0..14] of GLubyte = (  5,  0, 96, 32, 96,144,128,128,144, 96,  0,  0,  0,  0,  0);
Helvetica10_Character_232: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144,128,240,144, 96,  0, 32, 64,  0,  0);
Helvetica10_Character_233: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144,128,240,144, 96,  0, 64, 32,  0,  0);
Helvetica10_Character_234: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144,128,240,144, 96,  0, 80, 32,  0,  0);
Helvetica10_Character_235: array[0..14] of GLubyte = (  5,  0,  0,  0, 96,144,128,240,144, 96,  0, 80,  0,  0,  0);
Helvetica10_Character_236: array[0..14] of GLubyte = (  2,  0,  0,  0,128,128,128,128,128,128,  0,128,  0,  0,  0);
Helvetica10_Character_237: array[0..14] of GLubyte = (  2,  0,  0,  0,128,128,128,128,128,128,  0,128, 64,  0,  0);
Helvetica10_Character_238: array[0..14] of GLubyte = (  2,  0,  0,  0,128,128,128,128,128,128,  0, 64,128,  0,  0);
Helvetica10_Character_239: array[0..14] of GLubyte = (  2,  0,  0,  0, 64, 64, 64, 64, 64, 64,  0,160,  0,  0,  0);
Helvetica10_Character_240: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,120,144, 96, 80,  0,  0);
Helvetica10_Character_241: array[0..14] of GLubyte = (  5,  0,  0,  0,144,144,144,144,144,224,  0,160, 80,  0,  0);
Helvetica10_Character_242: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,112,  0, 32, 64,  0,  0);
Helvetica10_Character_243: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,112,  0, 32, 16,  0,  0);
Helvetica10_Character_244: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,112,  0, 80, 32,  0,  0);
Helvetica10_Character_245: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,112,  0, 80, 40,  0,  0);
Helvetica10_Character_246: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,136,136,136,112,  0, 80,  0,  0,  0);
Helvetica10_Character_247: array[0..14] of GLubyte = (  6,  0,  0,  0,  0, 32,  0,248,  0, 32,  0,  0,  0,  0,  0);
Helvetica10_Character_248: array[0..14] of GLubyte = (  6,  0,  0,  0,112,136,200,168,152,116,  0,  0,  0,  0,  0);
Helvetica10_Character_249: array[0..14] of GLubyte = (  5,  0,  0,  0,112,144,144,144,144,144,  0, 32, 64,  0,  0);
Helvetica10_Character_250: array[0..14] of GLubyte = (  5,  0,  0,  0,112,144,144,144,144,144,  0, 64, 32,  0,  0);
Helvetica10_Character_251: array[0..14] of GLubyte = (  5,  0,  0,  0,112,144,144,144,144,144,  0, 80, 32,  0,  0);
Helvetica10_Character_252: array[0..14] of GLubyte = (  5,  0,  0,  0,112,144,144,144,144,144,  0, 80,  0,  0,  0);
Helvetica10_Character_253: array[0..14] of GLubyte = (  5,  0,128, 64, 64, 96,160,160,144,144,  0, 32, 16,  0,  0);
Helvetica10_Character_254: array[0..14] of GLubyte = (  6,  0,128,128,176,200,136,136,200,176,128,128,  0,  0,  0);
Helvetica10_Character_255: array[0..14] of GLubyte = (  5,  0,128, 64, 64, 96,160,160,144,144,  0, 80,  0,  0,  0);

Helvetica10_Character_Map: array[0..255] of Pointer = (
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_033,
    @Helvetica10_Character_034, @Helvetica10_Character_035,
    @Helvetica10_Character_036, @Helvetica10_Character_037,
    @Helvetica10_Character_038, @Helvetica10_Character_039,
    @Helvetica10_Character_040, @Helvetica10_Character_041,
    @Helvetica10_Character_042, @Helvetica10_Character_043,
    @Helvetica10_Character_044, @Helvetica10_Character_045,
    @Helvetica10_Character_046, @Helvetica10_Character_047,
    @Helvetica10_Character_048, @Helvetica10_Character_049,
    @Helvetica10_Character_050, @Helvetica10_Character_051,
    @Helvetica10_Character_052, @Helvetica10_Character_053,
    @Helvetica10_Character_054, @Helvetica10_Character_055,
    @Helvetica10_Character_056, @Helvetica10_Character_057,
    @Helvetica10_Character_058, @Helvetica10_Character_059,
    @Helvetica10_Character_060, @Helvetica10_Character_061,
    @Helvetica10_Character_062, @Helvetica10_Character_063,
    @Helvetica10_Character_064, @Helvetica10_Character_065,
    @Helvetica10_Character_066, @Helvetica10_Character_067,
    @Helvetica10_Character_068, @Helvetica10_Character_069,
    @Helvetica10_Character_070, @Helvetica10_Character_071,
    @Helvetica10_Character_072, @Helvetica10_Character_073,
    @Helvetica10_Character_074, @Helvetica10_Character_075,
    @Helvetica10_Character_076, @Helvetica10_Character_077,
    @Helvetica10_Character_078, @Helvetica10_Character_079,
    @Helvetica10_Character_080, @Helvetica10_Character_081,
    @Helvetica10_Character_082, @Helvetica10_Character_083,
    @Helvetica10_Character_084, @Helvetica10_Character_085,
    @Helvetica10_Character_086, @Helvetica10_Character_087,
    @Helvetica10_Character_088, @Helvetica10_Character_089,
    @Helvetica10_Character_090, @Helvetica10_Character_091,
    @Helvetica10_Character_092, @Helvetica10_Character_093,
    @Helvetica10_Character_094, @Helvetica10_Character_095,
    @Helvetica10_Character_096, @Helvetica10_Character_097,
    @Helvetica10_Character_098, @Helvetica10_Character_099,
    @Helvetica10_Character_100, @Helvetica10_Character_101,
    @Helvetica10_Character_102, @Helvetica10_Character_103,
    @Helvetica10_Character_104, @Helvetica10_Character_105,
    @Helvetica10_Character_106, @Helvetica10_Character_107,
    @Helvetica10_Character_108, @Helvetica10_Character_109,
    @Helvetica10_Character_110, @Helvetica10_Character_111,
    @Helvetica10_Character_112, @Helvetica10_Character_113,
    @Helvetica10_Character_114, @Helvetica10_Character_115,
    @Helvetica10_Character_116, @Helvetica10_Character_117,
    @Helvetica10_Character_118, @Helvetica10_Character_119,
    @Helvetica10_Character_120, @Helvetica10_Character_121,
    @Helvetica10_Character_122, @Helvetica10_Character_123,
    @Helvetica10_Character_124, @Helvetica10_Character_125,
    @Helvetica10_Character_126, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_032, @Helvetica10_Character_032,
    @Helvetica10_Character_160, @Helvetica10_Character_161,
    @Helvetica10_Character_162, @Helvetica10_Character_163,
    @Helvetica10_Character_164, @Helvetica10_Character_165,
    @Helvetica10_Character_166, @Helvetica10_Character_167,
    @Helvetica10_Character_168, @Helvetica10_Character_169,
    @Helvetica10_Character_170, @Helvetica10_Character_171,
    @Helvetica10_Character_172, @Helvetica10_Character_173,
    @Helvetica10_Character_174, @Helvetica10_Character_175,
    @Helvetica10_Character_176, @Helvetica10_Character_177,
    @Helvetica10_Character_178, @Helvetica10_Character_179,
    @Helvetica10_Character_180, @Helvetica10_Character_181,
    @Helvetica10_Character_182, @Helvetica10_Character_183,
    @Helvetica10_Character_184, @Helvetica10_Character_185,
    @Helvetica10_Character_186, @Helvetica10_Character_187,
    @Helvetica10_Character_188, @Helvetica10_Character_189,
    @Helvetica10_Character_190, @Helvetica10_Character_191,
    @Helvetica10_Character_192, @Helvetica10_Character_193,
    @Helvetica10_Character_194, @Helvetica10_Character_195,
    @Helvetica10_Character_196, @Helvetica10_Character_197,
    @Helvetica10_Character_198, @Helvetica10_Character_199,
    @Helvetica10_Character_200, @Helvetica10_Character_201,
    @Helvetica10_Character_202, @Helvetica10_Character_203,
    @Helvetica10_Character_204, @Helvetica10_Character_205,
    @Helvetica10_Character_206, @Helvetica10_Character_207,
    @Helvetica10_Character_208, @Helvetica10_Character_209,
    @Helvetica10_Character_210, @Helvetica10_Character_211,
    @Helvetica10_Character_212, @Helvetica10_Character_213,
    @Helvetica10_Character_214, @Helvetica10_Character_215,
    @Helvetica10_Character_216, @Helvetica10_Character_217,
    @Helvetica10_Character_218, @Helvetica10_Character_219,
    @Helvetica10_Character_220, @Helvetica10_Character_221,
    @Helvetica10_Character_222, @Helvetica10_Character_223,
    @Helvetica10_Character_224, @Helvetica10_Character_225,
    @Helvetica10_Character_226, @Helvetica10_Character_227,
    @Helvetica10_Character_228, @Helvetica10_Character_229,
    @Helvetica10_Character_230, @Helvetica10_Character_231,
    @Helvetica10_Character_232, @Helvetica10_Character_233,
    @Helvetica10_Character_234, @Helvetica10_Character_235,
    @Helvetica10_Character_236, @Helvetica10_Character_237,
    @Helvetica10_Character_238, @Helvetica10_Character_239,
    @Helvetica10_Character_240, @Helvetica10_Character_241,
    @Helvetica10_Character_242, @Helvetica10_Character_243,
    @Helvetica10_Character_244, @Helvetica10_Character_245,
    @Helvetica10_Character_246, @Helvetica10_Character_247,
    @Helvetica10_Character_248, @Helvetica10_Character_249,
    @Helvetica10_Character_250, @Helvetica10_Character_251,
    @Helvetica10_Character_252, @Helvetica10_Character_253,
    @Helvetica10_Character_254, @Helvetica10_Character_255
);

ogFontHelvetica10: TGLUTFontDef = (
  charcnt: 256; height: 14; chars: @Helvetica10_Character_Map; xorig: 0; yorig: 3;
);

Helvetica12_Character_000: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_001: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_002: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_003: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_004: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_005: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_006: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_007: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_008: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_009: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_010: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_011: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_012: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_013: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_014: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_015: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_016: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_017: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_018: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_019: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_020: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_021: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_022: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_023: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_024: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_025: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_026: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_027: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_028: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_029: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_030: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_031: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_032: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_033: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64,  0, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica12_Character_034: array[0..16] of GLubyte = (  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 80, 80, 80,  0,  0,  0);
Helvetica12_Character_035: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 80, 80, 80,252, 40,252, 40, 40,  0,  0,  0,  0);
Helvetica12_Character_036: array[0..16] of GLubyte = (  7,  0,  0,  0, 16, 56, 84, 84, 20, 56, 80, 84, 56, 16,  0,  0,  0);
Helvetica12_Character_037: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 17,128, 10, 64, 10, 64,  9,128,  4,  0, 52,  0, 74,  0, 74,  0, 49,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_038: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 57,  0, 70,  0, 66,  0, 69,  0, 40,  0, 24,  0, 36,  0, 36,  0, 24,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_039: array[0..16] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 64, 32, 96,  0,  0,  0);
Helvetica12_Character_040: array[0..16] of GLubyte = (  4,  0, 16, 32, 32, 64, 64, 64, 64, 64, 64, 32, 32, 16,  0,  0,  0);
Helvetica12_Character_041: array[0..16] of GLubyte = (  4,  0,128, 64, 64, 32, 32, 32, 32, 32, 32, 64, 64,128,  0,  0,  0);
Helvetica12_Character_042: array[0..16] of GLubyte = (  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 80, 32, 80,  0,  0,  0);
Helvetica12_Character_043: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 16, 16,124, 16, 16,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_044: array[0..16] of GLubyte = (  4,  0,  0, 64, 32, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_045: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,  0,  0,  0,124,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_046: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_047: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,128,128, 64, 64, 64, 32, 32, 16, 16,  0,  0,  0);
Helvetica12_Character_048: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 68, 68, 56,  0,  0,  0);
Helvetica12_Character_049: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 16, 16, 16, 16, 16, 16, 16,112, 16,  0,  0,  0);
Helvetica12_Character_050: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,124, 64, 64, 32, 16,  8,  4, 68, 56,  0,  0,  0);
Helvetica12_Character_051: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68,  4,  4, 24,  4, 68, 56,  0,  0,  0);
Helvetica12_Character_052: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  8,  8,252,136, 72, 40, 40, 24,  8,  0,  0,  0);
Helvetica12_Character_053: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68,  4,  4,120, 64, 64,124,  0,  0,  0);
Helvetica12_Character_054: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68,100, 88, 64, 68, 56,  0,  0,  0);
Helvetica12_Character_055: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 32, 32, 16, 16, 16,  8,  8,  4,124,  0,  0,  0);
Helvetica12_Character_056: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 56, 68, 68, 56,  0,  0,  0);
Helvetica12_Character_057: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68,  4,  4, 60, 68, 68, 68, 56,  0,  0,  0);
Helvetica12_Character_058: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_059: array[0..16] of GLubyte = (  3,  0,  0,128, 64, 64,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_060: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 12, 48,192, 48, 12,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_061: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0,  0,124,  0,124,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_062: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 96, 24,  6, 24, 96,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_063: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 16,  0, 16, 16,  8,  8, 68, 68, 56,  0,  0,  0);
Helvetica12_Character_064: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0, 31,  0, 32,  0, 77,128, 83, 64, 81, 32, 81, 32, 73, 32, 38,160, 48, 64, 15,128,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_065: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0, 20,  0,  8,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_066: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,124, 66, 66, 66,124, 66, 66, 66,124,  0,  0,  0);
Helvetica12_Character_067: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,  0, 64,  0, 64,  0, 64,  0, 64,  0, 33,  0, 30,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_068: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0,124,  0, 66,  0, 65,  0, 65,  0, 65,  0, 65,  0, 65,  0, 66,  0,124,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_069: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,126, 64, 64, 64,126, 64, 64, 64,126,  0,  0,  0);
Helvetica12_Character_070: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 64, 64, 64, 64,124, 64, 64, 64,126,  0,  0,  0);
Helvetica12_Character_071: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 29,  0, 35,  0, 65,  0, 65,  0, 71,  0, 64,  0, 64,  0, 33,  0, 30,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_072: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 65,  0,127,  0, 65,  0, 65,  0, 65,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_073: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica12_Character_074: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68,  4,  4,  4,  4,  4,  4,  0,  0,  0);
Helvetica12_Character_075: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 65, 66, 68, 72,112, 80, 72, 68, 66,  0,  0,  0);
Helvetica12_Character_076: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,124, 64, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica12_Character_077: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 68, 64, 68, 64, 74, 64, 74, 64, 81, 64, 81, 64, 96,192, 96,192, 64, 64,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_078: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 67,  0, 69,  0, 69,  0, 73,  0, 81,  0, 81,  0, 97,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_079: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,128, 64,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_080: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 64, 64, 64, 64,124, 66, 66, 66,124,  0,  0,  0);
Helvetica12_Character_081: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,128, 33,  0, 66,128, 68,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_082: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 66, 66, 66, 68,124, 66, 66, 66,124,  0,  0,  0);
Helvetica12_Character_083: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 60, 66, 66,  2, 12, 48, 64, 66, 60,  0,  0,  0);
Helvetica12_Character_084: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 16, 16, 16, 16, 16, 16, 16, 16,254,  0,  0,  0);
Helvetica12_Character_085: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66, 66,  0,  0,  0);
Helvetica12_Character_086: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  8,  0, 20,  0, 20,  0, 34,  0, 34,  0, 34,  0, 65,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_087: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 17,  0, 17,  0, 17,  0, 42,128, 42,128, 36,128, 68, 64, 68, 64, 68, 64,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_088: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 34,  0, 34,  0, 20,  0,  8,  0, 20,  0, 34,  0, 34,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_089: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  8,  0,  8,  0,  8,  0, 20,  0, 34,  0, 34,  0, 65,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_090: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0,127,  0, 64,  0, 32,  0, 16,  0,  8,  0,  4,  0,  2,  0,  1,  0,127,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_091: array[0..16] of GLubyte = (  3,  0, 96, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 96,  0,  0,  0);
Helvetica12_Character_092: array[0..16] of GLubyte = (  4,  0,  0,  0,  0, 16, 16, 32, 32, 32, 64, 64,128,128,  0,  0,  0);
Helvetica12_Character_093: array[0..16] of GLubyte = (  3,  0,192, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,192,  0,  0,  0);
Helvetica12_Character_094: array[0..16] of GLubyte = (  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,136, 80, 32,  0,  0,  0,  0);
Helvetica12_Character_095: array[0..16] of GLubyte = (  7,  0,  0,254,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_096: array[0..16] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,192,128, 64,  0,  0,  0);
Helvetica12_Character_097: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56,  0,  0,  0,  0,  0);
Helvetica12_Character_098: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 88,100, 68, 68, 68,100, 88, 64, 64,  0,  0,  0);
Helvetica12_Character_099: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 64, 64, 64, 68, 56,  0,  0,  0,  0,  0);
Helvetica12_Character_100: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 52, 76, 68, 68, 68, 76, 52,  4,  4,  0,  0,  0);
Helvetica12_Character_101: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 64,124, 68, 68, 56,  0,  0,  0,  0,  0);
Helvetica12_Character_102: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64,224, 64, 48,  0,  0,  0);
Helvetica12_Character_103: array[0..16] of GLubyte = (  7,  0, 56, 68,  4, 52, 76, 68, 68, 68, 76, 52,  0,  0,  0,  0,  0);
Helvetica12_Character_104: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 68, 68, 68, 68, 68,100, 88, 64, 64,  0,  0,  0);
Helvetica12_Character_105: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64,  0, 64,  0,  0,  0);
Helvetica12_Character_106: array[0..16] of GLubyte = (  3,  0,128, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0, 64,  0,  0,  0);
Helvetica12_Character_107: array[0..16] of GLubyte = (  6,  0,  0,  0,  0, 68, 72, 80, 96, 96, 80, 72, 64, 64,  0,  0,  0);
Helvetica12_Character_108: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica12_Character_109: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 73,  0, 73,  0, 73,  0, 73,  0, 73,  0,109,  0, 82,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_110: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 68, 68, 68, 68, 68,100, 88,  0,  0,  0,  0,  0);
Helvetica12_Character_111: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 56,  0,  0,  0,  0,  0);
Helvetica12_Character_112: array[0..16] of GLubyte = (  7,  0, 64, 64, 64, 88,100, 68, 68, 68,100, 88,  0,  0,  0,  0,  0);
Helvetica12_Character_113: array[0..16] of GLubyte = (  7,  0,  4,  4,  4, 52, 76, 68, 68, 68, 76, 52,  0,  0,  0,  0,  0);
Helvetica12_Character_114: array[0..16] of GLubyte = (  4,  0,  0,  0,  0, 64, 64, 64, 64, 64, 96, 80,  0,  0,  0,  0,  0);
Helvetica12_Character_115: array[0..16] of GLubyte = (  6,  0,  0,  0,  0, 48, 72,  8, 48, 64, 72, 48,  0,  0,  0,  0,  0);
Helvetica12_Character_116: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 96, 64, 64, 64, 64, 64,224, 64, 64,  0,  0,  0);
Helvetica12_Character_117: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 52, 76, 68, 68, 68, 68, 68,  0,  0,  0,  0,  0);
Helvetica12_Character_118: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 16, 16, 40, 40, 68, 68, 68,  0,  0,  0,  0,  0);
Helvetica12_Character_119: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 34,  0, 34,  0, 85,  0, 73,  0, 73,  0,136,128,136,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_120: array[0..16] of GLubyte = (  6,  0,  0,  0,  0,132,132, 72, 48, 48, 72,132,  0,  0,  0,  0,  0);
Helvetica12_Character_121: array[0..16] of GLubyte = (  7,  0, 64, 32, 16, 16, 40, 40, 72, 68, 68, 68,  0,  0,  0,  0,  0);
Helvetica12_Character_122: array[0..16] of GLubyte = (  6,  0,  0,  0,  0,120, 64, 32, 32, 16,  8,120,  0,  0,  0,  0,  0);
Helvetica12_Character_123: array[0..16] of GLubyte = (  4,  0, 48, 64, 64, 64, 64, 64,128, 64, 64, 64, 64, 48,  0,  0,  0);
Helvetica12_Character_124: array[0..16] of GLubyte = (  3,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0,  0,  0);
Helvetica12_Character_125: array[0..16] of GLubyte = (  4,  0,192, 32, 32, 32, 32, 32, 16, 32, 32, 32, 32,192,  0,  0,  0);
Helvetica12_Character_126: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0,  0,  0,152,100,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_127: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_128: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_129: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_130: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_131: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_132: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_133: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_134: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_135: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_136: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_137: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_138: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_139: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_140: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_141: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_142: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_143: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_144: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_145: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_146: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_147: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_148: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_149: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_150: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_151: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_152: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_153: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_154: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_155: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_156: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_157: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_158: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_159: array[0..32] of GLubyte = ( 12,  0,  0,  0,  0,  0,  0,  0,  0, 85,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 65,  0,  0,  0, 85,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_160: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_161: array[0..16] of GLubyte = (  3,  0, 64, 64, 64, 64, 64, 64, 64, 64,  0, 64,  0,  0,  0,  0,  0);
Helvetica12_Character_162: array[0..16] of GLubyte = (  7,  0,  0,  0, 32, 56,100, 80, 80, 80, 84, 56,  8,  0,  0,  0,  0);
Helvetica12_Character_163: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 88, 36, 16, 16,120, 32, 32, 36, 24,  0,  0,  0);
Helvetica12_Character_164: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0,132,120, 72, 72,120,132,  0,  0,  0,  0,  0);
Helvetica12_Character_165: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 16, 16,124, 16,124, 16, 40, 68, 68,  0,  0,  0);
Helvetica12_Character_166: array[0..16] of GLubyte = (  3,  0,  0, 64, 64, 64, 64,  0,  0,  0, 64, 64, 64, 64,  0,  0,  0);
Helvetica12_Character_167: array[0..16] of GLubyte = (  6,  0,112,136,  8, 48, 72,136,136,144, 96,128,136,112,  0,  0,  0);
Helvetica12_Character_168: array[0..16] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,160,  0,  0,  0);
Helvetica12_Character_169: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 31,  0, 32,128, 78, 64, 81, 64, 80, 64, 81, 64, 78, 64, 32,128, 31,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_170: array[0..16] of GLubyte = (  5,  0,  0,  0,  0,  0,  0,  0,  0,112,  0, 80, 16,112,  0,  0,  0);
Helvetica12_Character_171: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 20, 40, 80, 40, 20,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_172: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,  0,  0,  2,  2,  2,126,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_173: array[0..16] of GLubyte = (  5,  0,  0,  0,  0,  0,  0,  0,240,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_174: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 31,  0, 32,128, 74, 64, 74, 64, 76, 64, 74, 64, 78, 64, 32,128, 31,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_175: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,240,  0,  0,  0);
Helvetica12_Character_176: array[0..16] of GLubyte = (  5,  0,  0,  0,  0,  0,  0,  0,  0, 96,144,144, 96,  0,  0,  0,  0);
Helvetica12_Character_177: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,124,  0, 16, 16,124, 16, 16,  0,  0,  0,  0,  0);
Helvetica12_Character_178: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,240, 64, 32,144, 96,  0,  0,  0,  0);
Helvetica12_Character_179: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0,192, 32, 64, 32,224,  0,  0,  0,  0);
Helvetica12_Character_180: array[0..16] of GLubyte = (  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,128, 64,  0,  0);
Helvetica12_Character_181: array[0..16] of GLubyte = (  7,  0, 64, 64, 64,116, 76, 68, 68, 68, 68, 68,  0,  0,  0,  0,  0);
Helvetica12_Character_182: array[0..16] of GLubyte = (  7,  0, 40, 40, 40, 40, 40, 40,104,232,232,232,104, 60,  0,  0,  0);
Helvetica12_Character_183: array[0..16] of GLubyte = (  3,  0,  0,  0,  0,  0,  0,  0, 64,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_184: array[0..16] of GLubyte = (  3,  0,192, 32, 32, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_185: array[0..16] of GLubyte = (  4,  0,  0,  0,  0,  0,  0,  0, 32, 32, 32, 96, 32,  0,  0,  0,  0);
Helvetica12_Character_186: array[0..16] of GLubyte = (  5,  0,  0,  0,  0,  0,  0,  0,  0,112,  0,112, 80,112,  0,  0,  0);
Helvetica12_Character_187: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 80, 40, 20, 40, 80,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_188: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 39,128, 21,  0, 19,  0, 73,  0, 68,  0, 68,  0,194,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_189: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 71,128, 34,  0, 17,  0, 20,128, 75,  0, 72,  0, 68,  0,194,  0, 65,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_190: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 33,  0, 23,128, 21,  0, 11,  0,201,  0, 36,  0, 68,  0, 34,  0,225,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_191: array[0..16] of GLubyte = (  7,  0, 56, 68, 68, 32, 32, 16, 16,  0, 16,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_192: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0,  8,  0,  8,  0,  0,  0,  8,  0, 16,  0);
Helvetica12_Character_193: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0,  8,  0,  8,  0,  0,  0,  8,  0,  4,  0);
Helvetica12_Character_194: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0,  8,  0,  8,  0,  0,  0, 20,  0,  8,  0);
Helvetica12_Character_195: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0,  8,  0,  8,  0,  0,  0, 20,  0, 10,  0);
Helvetica12_Character_196: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0,  8,  0,  8,  0,  0,  0, 20,  0,  0,  0);
Helvetica12_Character_197: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 65,  0, 65,  0, 62,  0, 34,  0, 34,  0, 20,  0,  8,  0,  8,  0,  8,  0, 20,  0,  8,  0);
Helvetica12_Character_198: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 71,192, 68,  0, 68,  0, 60,  0, 39,192, 36,  0, 20,  0, 20,  0, 15,192,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_199: array[0..32] of GLubyte = (  9,  0,  0, 24,  0,  4,  0,  4,  0, 30,  0, 33,  0, 64,  0, 64,  0, 64,  0, 64,  0, 64,  0, 33,  0, 30,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_200: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,126, 64, 64, 64,126, 64, 64, 64,126,  0,  8, 16);
Helvetica12_Character_201: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,126, 64, 64, 64,126, 64, 64, 64,126,  0,  8,  4);
Helvetica12_Character_202: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,126, 64, 64, 64,126, 64, 64, 64,126,  0, 20,  8);
Helvetica12_Character_203: array[0..16] of GLubyte = (  8,  0,  0,  0,  0,126, 64, 64, 64,126, 64, 64, 64,126,  0, 20,  0);
Helvetica12_Character_204: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0, 64,128);
Helvetica12_Character_205: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0, 64, 32);
Helvetica12_Character_206: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0,160, 64);
Helvetica12_Character_207: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64, 64, 64,  0,160,  0);
Helvetica12_Character_208: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0,124,  0, 66,  0, 65,  0, 65,  0, 241,  0, 65,  0, 65,  0, 66,  0,124,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_209: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0, 65,  0, 67,  0, 69,  0, 69,  0, 73,  0, 81,  0, 81,  0, 97,  0, 65,  0,  0,  0, 20,  0, 10,  0);
Helvetica12_Character_210: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,128, 64,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0,  4,  0,  8,  0);
Helvetica12_Character_211: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,128, 64,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0,  4,  0,  2,  0);
Helvetica12_Character_212: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,128, 64,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0, 10,  0,  4,  0);
Helvetica12_Character_213: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,128, 64,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0, 20,  0, 10,  0);
Helvetica12_Character_214: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,  0,  0, 30,  0, 33,  0, 64,128, 64,128, 64,128, 64,128, 64,128, 33,  0, 30,  0,  0,  0, 18,  0,  0,  0);
Helvetica12_Character_215: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 68, 40, 16, 40, 68,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_216: array[0..32] of GLubyte = ( 10,  0,  0,  0,  0,  0,  0,128,  0, 94,  0, 33,  0, 80,128, 72,128, 68,128, 68,128, 66,128, 33,  0, 30,128,  0, 64,  0,  0,  0,  0);
Helvetica12_Character_217: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66, 66,  0,  8, 16);
Helvetica12_Character_218: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66, 66,  0,  8,  4);
Helvetica12_Character_219: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66, 66,  0, 20,  8);
Helvetica12_Character_220: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 60, 66, 66, 66, 66, 66, 66, 66, 66,  0, 36,  0);
Helvetica12_Character_221: array[0..32] of GLubyte = (  9,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  8,  0,  8,  0,  8,  0, 20,  0, 34,  0, 34,  0, 65,  0, 65,  0,  0,  0,  8,  0,  4,  0);
Helvetica12_Character_222: array[0..16] of GLubyte = (  8,  0,  0,  0,  0, 64, 64,124, 66, 66, 66,124, 64, 64,  0,  0,  0);
Helvetica12_Character_223: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 88, 68, 68, 68, 88, 68, 68, 68, 56,  0,  0,  0);
Helvetica12_Character_224: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56,  0,  8, 16,  0,  0);
Helvetica12_Character_225: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56,  0, 16,  8,  0,  0);
Helvetica12_Character_226: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56,  0, 40, 16,  0,  0);
Helvetica12_Character_227: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56,  0, 40, 20,  0,  0);
Helvetica12_Character_228: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56,  0, 40,  0,  0,  0);
Helvetica12_Character_229: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 58, 68, 68, 60,  4, 68, 56, 24, 36, 24,  0,  0);
Helvetica12_Character_230: array[0..32] of GLubyte = ( 11,  0,  0,  0,  0,  0,  0,  0,  0, 59,128, 68, 64, 68,  0, 63,192,  4, 64, 68, 64, 59,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_231: array[0..16] of GLubyte = (  7,  0, 48,  8, 16, 56, 68, 64, 64, 64, 68, 56,  0,  0,  0,  0,  0);
Helvetica12_Character_232: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 64,124, 68, 68, 56,  0, 16, 32,  0,  0);
Helvetica12_Character_233: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 64,124, 68, 68, 56,  0, 16,  8,  0,  0);
Helvetica12_Character_234: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 64,124, 68, 68, 56,  0, 40, 16,  0,  0);
Helvetica12_Character_235: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 64,124, 68, 68, 56,  0, 40,  0,  0,  0);
Helvetica12_Character_236: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64,  0, 64,128,  0,  0);
Helvetica12_Character_237: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64,  0, 64, 32,  0,  0);
Helvetica12_Character_238: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64,  0,160, 64,  0,  0);
Helvetica12_Character_239: array[0..16] of GLubyte = (  3,  0,  0,  0,  0, 64, 64, 64, 64, 64, 64, 64,  0,160,  0,  0,  0);
Helvetica12_Character_240: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 60,  4, 40, 24, 52,  0,  0);
Helvetica12_Character_241: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 68, 68, 68, 68, 68,100, 88,  0, 40, 20,  0,  0);
Helvetica12_Character_242: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 56,  0, 16, 32,  0,  0);
Helvetica12_Character_243: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 56,  0, 16,  8,  0,  0);
Helvetica12_Character_244: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 56,  0, 40, 16,  0,  0);
Helvetica12_Character_245: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 56,  0, 40, 20,  0,  0);
Helvetica12_Character_246: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 56, 68, 68, 68, 68, 68, 56,  0, 40,  0,  0,  0);
Helvetica12_Character_247: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,  0, 16,  0,124,  0, 16,  0,  0,  0,  0,  0,  0);
Helvetica12_Character_248: array[0..16] of GLubyte = (  7,  0,  0,  0,  0,184, 68,100, 84, 76, 68, 58,  0,  0,  0,  0,  0);
Helvetica12_Character_249: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 52, 76, 68, 68, 68, 68, 68,  0, 16, 32,  0,  0);
Helvetica12_Character_250: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 52, 76, 68, 68, 68, 68, 68,  0, 16,  8,  0,  0);
Helvetica12_Character_251: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 52, 76, 68, 68, 68, 68, 68,  0, 40, 16,  0,  0);
Helvetica12_Character_252: array[0..16] of GLubyte = (  7,  0,  0,  0,  0, 52, 76, 68, 68, 68, 68, 68,  0, 40,  0,  0,  0);
Helvetica12_Character_253: array[0..16] of GLubyte = (  7,  0, 64, 32, 16, 16, 40, 40, 72, 68, 68, 68,  0, 16,  8,  0,  0);
Helvetica12_Character_254: array[0..16] of GLubyte = (  7,  0, 64, 64, 64, 88,100, 68, 68, 68,100, 88, 64, 64,  0,  0,  0);
Helvetica12_Character_255: array[0..16] of GLubyte = (  7,  0, 96, 16, 16, 16, 24, 40, 40, 36, 68, 68,  0, 40,  0,  0,  0);

Helvetica12_Character_Map: array[0..255] of Pointer = (
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_033,
    @Helvetica12_Character_034, @Helvetica12_Character_035,
    @Helvetica12_Character_036, @Helvetica12_Character_037,
    @Helvetica12_Character_038, @Helvetica12_Character_039,
    @Helvetica12_Character_040, @Helvetica12_Character_041,
    @Helvetica12_Character_042, @Helvetica12_Character_043,
    @Helvetica12_Character_044, @Helvetica12_Character_045,
    @Helvetica12_Character_046, @Helvetica12_Character_047,
    @Helvetica12_Character_048, @Helvetica12_Character_049,
    @Helvetica12_Character_050, @Helvetica12_Character_051,
    @Helvetica12_Character_052, @Helvetica12_Character_053,
    @Helvetica12_Character_054, @Helvetica12_Character_055,
    @Helvetica12_Character_056, @Helvetica12_Character_057,
    @Helvetica12_Character_058, @Helvetica12_Character_059,
    @Helvetica12_Character_060, @Helvetica12_Character_061,
    @Helvetica12_Character_062, @Helvetica12_Character_063,
    @Helvetica12_Character_064, @Helvetica12_Character_065,
    @Helvetica12_Character_066, @Helvetica12_Character_067,
    @Helvetica12_Character_068, @Helvetica12_Character_069,
    @Helvetica12_Character_070, @Helvetica12_Character_071,
    @Helvetica12_Character_072, @Helvetica12_Character_073,
    @Helvetica12_Character_074, @Helvetica12_Character_075,
    @Helvetica12_Character_076, @Helvetica12_Character_077,
    @Helvetica12_Character_078, @Helvetica12_Character_079,
    @Helvetica12_Character_080, @Helvetica12_Character_081,
    @Helvetica12_Character_082, @Helvetica12_Character_083,
    @Helvetica12_Character_084, @Helvetica12_Character_085,
    @Helvetica12_Character_086, @Helvetica12_Character_087,
    @Helvetica12_Character_088, @Helvetica12_Character_089,
    @Helvetica12_Character_090, @Helvetica12_Character_091,
    @Helvetica12_Character_092, @Helvetica12_Character_093,
    @Helvetica12_Character_094, @Helvetica12_Character_095,
    @Helvetica12_Character_096, @Helvetica12_Character_097,
    @Helvetica12_Character_098, @Helvetica12_Character_099,
    @Helvetica12_Character_100, @Helvetica12_Character_101,
    @Helvetica12_Character_102, @Helvetica12_Character_103,
    @Helvetica12_Character_104, @Helvetica12_Character_105,
    @Helvetica12_Character_106, @Helvetica12_Character_107,
    @Helvetica12_Character_108, @Helvetica12_Character_109,
    @Helvetica12_Character_110, @Helvetica12_Character_111,
    @Helvetica12_Character_112, @Helvetica12_Character_113,
    @Helvetica12_Character_114, @Helvetica12_Character_115,
    @Helvetica12_Character_116, @Helvetica12_Character_117,
    @Helvetica12_Character_118, @Helvetica12_Character_119,
    @Helvetica12_Character_120, @Helvetica12_Character_121,
    @Helvetica12_Character_122, @Helvetica12_Character_123,
    @Helvetica12_Character_124, @Helvetica12_Character_125,
    @Helvetica12_Character_126, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_032, @Helvetica12_Character_032,
    @Helvetica12_Character_160, @Helvetica12_Character_161,
    @Helvetica12_Character_162, @Helvetica12_Character_163,
    @Helvetica12_Character_164, @Helvetica12_Character_165,
    @Helvetica12_Character_166, @Helvetica12_Character_167,
    @Helvetica12_Character_168, @Helvetica12_Character_169,
    @Helvetica12_Character_170, @Helvetica12_Character_171,
    @Helvetica12_Character_172, @Helvetica12_Character_173,
    @Helvetica12_Character_174, @Helvetica12_Character_175,
    @Helvetica12_Character_176, @Helvetica12_Character_177,
    @Helvetica12_Character_178, @Helvetica12_Character_179,
    @Helvetica12_Character_180, @Helvetica12_Character_181,
    @Helvetica12_Character_182, @Helvetica12_Character_183,
    @Helvetica12_Character_184, @Helvetica12_Character_185,
    @Helvetica12_Character_186, @Helvetica12_Character_187,
    @Helvetica12_Character_188, @Helvetica12_Character_189,
    @Helvetica12_Character_190, @Helvetica12_Character_191,
    @Helvetica12_Character_192, @Helvetica12_Character_193,
    @Helvetica12_Character_194, @Helvetica12_Character_195,
    @Helvetica12_Character_196, @Helvetica12_Character_197,
    @Helvetica12_Character_198, @Helvetica12_Character_199,
    @Helvetica12_Character_200, @Helvetica12_Character_201,
    @Helvetica12_Character_202, @Helvetica12_Character_203,
    @Helvetica12_Character_204, @Helvetica12_Character_205,
    @Helvetica12_Character_206, @Helvetica12_Character_207,
    @Helvetica12_Character_208, @Helvetica12_Character_209,
    @Helvetica12_Character_210, @Helvetica12_Character_211,
    @Helvetica12_Character_212, @Helvetica12_Character_213,
    @Helvetica12_Character_214, @Helvetica12_Character_215,
    @Helvetica12_Character_216, @Helvetica12_Character_217,
    @Helvetica12_Character_218, @Helvetica12_Character_219,
    @Helvetica12_Character_220, @Helvetica12_Character_221,
    @Helvetica12_Character_222, @Helvetica12_Character_223,
    @Helvetica12_Character_224, @Helvetica12_Character_225,
    @Helvetica12_Character_226, @Helvetica12_Character_227,
    @Helvetica12_Character_228, @Helvetica12_Character_229,
    @Helvetica12_Character_230, @Helvetica12_Character_231,
    @Helvetica12_Character_232, @Helvetica12_Character_233,
    @Helvetica12_Character_234, @Helvetica12_Character_235,
    @Helvetica12_Character_236, @Helvetica12_Character_237,
    @Helvetica12_Character_238, @Helvetica12_Character_239,
    @Helvetica12_Character_240, @Helvetica12_Character_241,
    @Helvetica12_Character_242, @Helvetica12_Character_243,
    @Helvetica12_Character_244, @Helvetica12_Character_245,
    @Helvetica12_Character_246, @Helvetica12_Character_247,
    @Helvetica12_Character_248, @Helvetica12_Character_249,
    @Helvetica12_Character_250, @Helvetica12_Character_251,
    @Helvetica12_Character_252, @Helvetica12_Character_253,
    @Helvetica12_Character_254, @Helvetica12_Character_255
);

ogFontHelvetica12: TGLUTFontDef = (
  charcnt: 256; height: 16; chars: @Helvetica12_Character_Map; xorig: 0; yorig: 4;
);

procedure glutBitmapString(fontID: integer; const s: string);
var
  I:    integer;
  x:    GLfloat;
  font: PGLUTFontDef;
  face: PGLubyte;
begin
  case fontid of
    GLUT_BITMAP_HELVETICA_10:
        font := @ogFontHelvetica10;
    GLUT_BITMAP_HELVETICA_12:
        font := @ogFontHelvetica12;
    else
      raise Exception.Create('Unsupported GLUT font ' + IntToStr(fontID));
  end;

  glPushClientAttrib( GL_CLIENT_PIXEL_STORE_BIT );
  glPixelStorei( GL_UNPACK_SWAP_BYTES,  GL_FALSE );
  glPixelStorei( GL_UNPACK_LSB_FIRST,   GL_FALSE );
  glPixelStorei( GL_UNPACK_ROW_LENGTH,  0        );
  glPixelStorei( GL_UNPACK_SKIP_ROWS,   0        );
  glPixelStorei( GL_UNPACK_SKIP_PIXELS, 0        );
  glPixelStorei( GL_UNPACK_ALIGNMENT,   1        );

  (*
   * Step through the string, drawing each character.
   * A newline will simply translate the next character"s insertion
   * point back to the start of the line and down one line.
  *)
  x := 0.0;

  for I := 1 to Length(s) do
    if s[I] = #13 then begin
      glBitmap(0, 0, 0, 0, -x, -font^.height, nil);
      x := 0.0;
    end
    else begin { Not an EOL, draw the bitmap character }
      face := font^.chars[ord(s[I])];
      glBitmap(face^, font^.height, font^.xorig, font^.yorig,
        face^, 0.0, PGLubyte(Cardinal(face) + 1));
      x := x + face^;
    end;

  glPopClientAttrib();
end;

end.
