#!/bin/sh

# emap (expand map)
# Jun 13 2003 more public domain software by the MastaMappa
# splits .map files long lines into 2 point segments

awk '
BEGIN { FS = OFS = "," }
$1 ~ /^[MF]$/ {
	h = $1 "," $2 "," $3 ",2"
	o = 5
	for (i = 1; i < $4; i++)
	{
		print h, $(o), $(o+1), $(o+2), $(o+3), $(o+4), $(o+5)
		o += 3
	}
	next
	}
	{ print }' $*
